# This is workflow name
 name: Hello workflow

# runs on a trigger
 on:
    push:
      branches: [main]

# these are jobs inside the workflow
 jobs:

# this is the name of the job
#job 1
    greet:
  # this is gitbub runner
      runs-on: ubuntu-latest
      steps:
        - name: say hello to users
          run: echo "Hello Dosto"
        - name: say hello to username
          run: echo "Hello $USER"
  #job 2
     details:
       runs-on: ubuntu-latest
       steps:
        name: show what is the version o Python, docker etc
        run: docker --version && python --version
       
